apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-l2hf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-l2hf
    app.kubernetes.io/part-of: tkrw-pr712-0075-0040-app
  name: devfile-sample-l2hf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-l2hf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-l2hf
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0040-tenant/tkrw-pr712-0075-0040-app/devfile-sample-l2hf@sha256:101e3ed7a7fa07cdf72a2c5c16a0fa4cd1c441ec8930eb30505c895bcf15cbf1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
